#!/bin/sh

share_dir="${XDG_DATA_HOME}/@PKGNAME@"
state_dir="${XDG_STATE_HOME}/@PKGNAME@"

mkdir -p "${state_dir}"

if [ ! -d "${share_dir}" ]; then
	cp -R /usr/share/@PKGNAME@/config_linux "${share_dir}"
fi

cd "/usr/libexec/@PKGNAME@"

exec java \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dlog.level=ALL \
	-Dfile.encoding=utf-8 \
	-noverify \
	-Xmx1G \
	--add-modules=ALL-SYSTEM \
	--add-opens java.base/java.util=ALL-UNNAMED \
	--add-opens java.base/java.lang=ALL-UNNAMED \
	-jar ./plugins/org.eclipse.equinox.launcher_*.jar \
	-configuration ${share_dir} \
	-data "${state_dir}" \
	"$@"
